### ISSUE TITLE
Blog Down

### ISSUE THREAD

**Issue by than3-bits** [InvexGaming/IdentityLogger#3]
Hi Mo, I recently ran across your blog post about IdentityLogger, though I realize it might be dated at this point I thought I'd leave a comment here since the application on the site seems to be broken (or is under extreme load, maybe from being linked at HN).

While I can appreciate the rancor you have towards cheaters, and that it was sufficient to get you to write this solution, did you consider alternative approaches? 

The reason I ask is Cheating is a famous cursed problem, but like most cursed problems you can often relax your requirements and solve the underlying problem better than trying to approach it outright directly. Super Smash Brothers is a perfect example (see the GameDev conf talks on Cursed Problems)

The problem with cat-mouse games is that its a never-ending loop, and the time/labor asymmetry is not in your favor. You'll lose every time given sufficient time when it costs you more to remediate than it does for them to attack. Same parallels can be found in cybersecurity. If you can avoid it you don't want to be in that game.

Also, any solution where data collection occurs as any kind of verification is going to make you a target of bad actors, since you become a watering hole as well for valuable information.

From your blog its clear you've drawn a hard line in the sand against cheaters in general. If someone cheats they shouldn't be on your server, and I can get behind that line of reasoning if it can be done effectively which in fairness, IdentityLogger isn't a permanent solution, and neither is banning.

Lets re-examine the problem scope:
First, Is it the fact that they are cheating that causes the issues, or is it the fact that they are cheating against other 'people', that cause the issues? I would think the latter in this case because who cares if you cheat against bots; no ones harmed and people can play games however they want when no ones harmed.

Lets take the perspective of a cheater, what is the very first thing they need to do to get into this attacker mindset. They try to play and when they can't play, it starts. They try to play and they instead get a feedback message that they are blocked/banned. 

I hope you see where I"m going here ... in other words, you are giving them the feedback information that they need to move to the next step in their reasoning towards attacking (because they can't play, and they wanted to). 

If you don't know there's a problem you can't take action towards solving it.

What would happen if instead of banning, they simply got silently routed to a separate server process where the only queued players are cheaters, bots, or low reputation devices? One where the server accentuates the annoying players aspects of low quality servers (one just the cheaters), where resources (your cost) are minimized.

How would they know anything has changed, they can still play. Other than by spending a lot of time competing with similar like-minded players (which still meets with your mission statement).  All things being equal, competition isn't biased in a game where the only people are those who cheat.

Would this help that labor asymmetry you face? Can you add personal costs to discourage cheating in this way (without them noticing?). If they notice, someone in the pool is going to have the expertise to drain your resources, and it only takes one to find a bypass and spread it widely (distributing labor for free). You'll also be lulled into a false sense of security with the existing strategy, and have no visibility on the people who pass all your checks except through manual perspiration and review, and these people may be so incensed to try this strategy in reverse.  All in all, the false negative is often worse than false positives. 

Now there is some further design that you'd need work through, to do so in a way that they can't easily check to verify a change has occurred server side, like what they might do when coordinating with another account to play together; but this approach is entirely doable; you could even have them automatically fall off that disadvantaged server list if you have a way to check if they continue cheating after a period of time (i.e. that disadvantaged server instead of banning immediately on a trigger, simply warns the admins silently with a graduated response countdown, or time out period in the corner).

By taking this type of approach, relaxing your requirements, you can convert this from a interrupt driven response (which costs the most), to a scheduled maintenance response (monitoring on your schedule), and you may even discourage those individuals from continuing if you add enough personal cost when they demonstrate this maladaptive type of behavior.

**Comment by mobeigi** [comment]
Hey @than3-bits,

Thanks for the response! Sorry the site is down, but of a pain for sure haha!
You make a great comment, would be amazing if you could repost it on the blog as a comment 🙇 The site seems to be somewhat available now albeit slow.

To answer your question, the methods you mention to be less reactive and more flexible are quite sound and honestly make it easier. I would prefer to take a more relaxed approach when it comes to managing cheaters but one thing I learnt is they are relentless and basically never give up. It seems there is a endless supply and some are very dedicated at circumventing any restrictions or detections you put in place. That's what sadly leads to the cat and mouse game which is time consuming and frustrating.  

Routing to another server is an interesting idea but the players would know and I've had some disgruntled players DDOS the server or the community forums as a result of being banned or warned etc. I have no doubt they would do the same thing if they were redirected to another server instead.

**Comment by than3-bits** [comment]
No worries, I'll see about reposting there now that its back up. Feel free to close this.

As for routing and them finding out, if there's a load balancer (like haproxy) out front then it would be fairly challenging for them to glean its a different server without information leaks (which if set up properly would ideally be transparent from the client side). You can also pass traffic through to a wrapper if something more advanced is needed. I've set up basic python wrappers like that for a few containerized applications (where different instances are set up identically and the balancer handles the logic)

We commonly do this normally to scale up (vertically) or out (horizontally) with a distributed back end that has sticky connections on clients, and other useful features like pool draining (for zero downtime upgrades). Sometimes its just a simple redirect, sometimes it is transparent, depends on the requirements.

It looks like the comment submissions are still down. Tried to submit this with a bit more info, had a unknown error with t is undefined, in a notification popup, and then it said it was spam on the second attempt (after the first attempt failed to submit). Seems something is still broken.

> They basically never give up

I've found that's often only true when they can't play and feel spiteful (and are getting to that point from direct feedback from the ban). 

Perception is very finicky when things still work, and they just don't work as well. Its hard to notice a concrete difference.

It is inherently hard to attribute cause and effect and notice very subtle changes, and in the land of transient network issues, and other computing failures, where there is doubt that something is related, they'll be second guessing every assumption they make and spinning their wheels; which helps dramatically with that labor asymmetry. It also helps quite a lot that you control your infrastructure. 

You can choose to offer Less visibility, less information, with proper application you leave them only a guess and check error prone approach, and each major error on their part makes it easier. If they can still technically play, but something is off, is the juice pouring over the public data, and other technical aspects worth the squeeze (where nothing stands out because its all handled seamlessly behind the LB)?

If you were so inclined, you could lay false trails (or honeypots) in some of the public facing code to spin their wheels further, or out themselves, or use that against them pre-emptively, such as setting randomized functional changes on a drip tickler/timer (which rotates, forcing them to start over from scratch in their research and assumptions).  

Some people like challenges, some challenges are pipe dreams.  If the cost is high enough for them, they'll go for easier places; and if they can still play its really hard for them to think they were banned. It is at most just a suspicion, where you control that information.  

I'm generally not a big fan of shadow bans, but for a subset of problematic individuals who are unwilling to follow basic guidelines they agreed to; it has to be done. The alternative is imposing arbitrary excessive costs on yourself, where no one gets to benefit (as the server would be shut down).
